name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: {{ env.NODE_VERSION }}
      - run: npm i
      - run: npm run build --if-present
      - run: npm test
